import { build, fake } from "test-data-bot";

const adorableAvatarApi = "https://i.pravatar.cc";

const randomFromArray = <T>(array: T[]) =>
  array[Math.floor(Math.random() * array.length)];

const studentBuilder = build("Student")
  .fields({
    name: fake((f) => f.name.findName()),
    lecturesAttended: fake((f) => f.random.number({ min: 0, max: 25 })),
    totalLectures: fake((f) => f.random.number({ min: 15, max: 30 })),
    marks: fake((f) =>
      [...Array(f.random.number({ min: 1, max: 5 }))]
        .map((e, i) => {
          const subject =
            randomFromArray<{ code: string; title: string }>(subjects);
          return {
            code: subject.code,
            subjectTitle: subject.title,
            totalMarks: f.random.number({ min: 90, max: 100 }),
            markesObtained: f.random.number({ min: 30, max: 100 }),
          };
        })
        .reduce(
          (acc, { code, subjectTitle, totalMarks, markesObtained }) => ({
            ...acc,
            [code]: {
              subjectTitle,
              totalMarks,
              markesObtained,
            },
          }),
          {}
        )
    ),
  })
  .map((student) => ({
    ...student,
    avatarURL: `${adorableAvatarApi}/200?u=${student.name}`,
  }));

const range = (len) => {
  const arr = [];
  for (let i = 0; i < len; i++) {
    arr.push(i);
  }
  return arr;
};

export default function makeData(...lens: [number]): [Student] {
  const makeDataLevel = (depth = 0) => {
    const len = lens[depth];
    return range(len).map((d) => {
      return {
        ...studentBuilder(),
        subRows: lens[depth + 1] ? makeDataLevel(depth + 1) : undefined,
      };
    });
  };

  return makeDataLevel();
}

const subjects = [
  { code: "AFST", title: "African/African Amer Studies" },
  { code: "ABLE", title: "Ability Based Learning Environ" },
  { code: "ACAD", title: "University Program" },
  { code: "ACCM", title: "Anesthesiology & Critical Care" },
  { code: "ACCT", title: "Accounting" },
  { code: "ACES", title: "Acad & Comput Excellence Sem" },
  { code: "ADHT", title: "Adolescent Health" },
  { code: "ADVC", title: "Advanced Core" },
  { code: "AIOM", title: "Asian Inst of Mgt, Philippines" },
  { code: "AKKD", title: "Akkadian" },
  { code: "AMST", title: "American Studies" },
  { code: "ANAT", title: "Anatomy" },
  { code: "ANEE", title: "Ancient Near East and Egyptian Studies" },
  { code: "ANES", title: "Anesthesiology" },
  { code: "ANTH", title: "Anthropology" },
  { code: "APMU", title: "Applied Music" },
  { code: "ARAB", title: "Arabic" },
  { code: "ARSC", title: "College Scholars Program" },
  { code: "ARTH", title: "Art History" },
  { code: "ARTK", title: "Computers in Visual Arts" },
  { code: "ARTS", title: "Art Studio" },
  { code: "ASCV", title: "Asian Civilization" },
  { code: "ASIA", title: "Asian Studies" },
  { code: "ASTR", title: "Astronomy" },
  { code: "BAFI", title: "Banking & Finance" },
  { code: "BASC", title: "Basic Science Curriculum" },
  { code: "BETH", title: "Bioethics" },
  { code: "BIOC", title: "Biochemistry" },
  { code: "BIOL", title: "Biology" },
  { code: "BIOM", title: "Biometry" },
  { code: "BIOS", title: "Bioscience Entrepreneurship" },
  { code: "BLAW", title: "Business Law" },
  { code: "BOCR", title: "Basics of Clinical Reasoning" },
  { code: "BSTP", title: "Biomedical Sciences Train Prog" },
  { code: "BTEC", title: "Business Technology" },
  { code: "CAPG", title: "Core Academic Program" },
  { code: "CARD", title: "Cardiology" },
  { code: "CARE", title: "Primary Care Courses" },
  { code: "CBIO", title: "Cellular & Molecular Biology" },
  { code: "CFNU", title: "Community Frontier Nursing" },
  { code: "CH	 ", title: "  Chemistry" },
  { code: "CHEM", title: "Chemistry" },
  { code: "CHIN", title: "Chinese" },
  { code: "CHST", title: "Childhood Studies" },
  { code: "CIAR", title: "Cleveland Institute of Art" },
  { code: "CLBY", title: "Cell Biology" },
  { code: "CLIN", title: "Clinical Curriculum" },
  { code: "CLMI", title: "Clinical Med & Internships" },
  { code: "CLSC", title: "Classics" },
  { code: "CMED", title: "Clinical Medicine - CCLCM" },
  { code: "CMPL", title: "Comparative Literature" },
  { code: "CMPS", title: "Computing/Information Science" },
  { code: "CNCR", title: "Cancer Center" },
  { code: "COGS", title: "Cognitive Science" },
  { code: "COLS", title: "Graduate Summer Research" },
  { code: "COMP", title: "Patient Based Clinicl Cmprhnsv" },
  { code: "COOP", title: "Cooperative Education" },
  { code: "COPE", title: "Copenhagen Bus. Schl, Denmark" },
  { code: "CORE", title: "Core Clinical Medicine" },
  { code: "COSI", title: "Communication Sciences" },
  { code: "CRSP", title: "Clinical Research Scholars Prg" },
  { code: "CSDS", title: "Computer and Data Sciences" },
  { code: "DANC", title: "Dance" },
  { code: "DART", title: "Dramatic Arts" },
  { code: "DENC", title: "Dentistry - Clinical" },
  { code: "DEND", title: "Dentistry - Didactic" },
  { code: "DENF", title: "Dentistry - Faculty" },
  { code: "DENT", title: "Dentistry" },
  { code: "DERM", title: "Dermatology" },
  { code: "DESN", title: "Design & Innovation" },
  { code: "DGMS", title: "General Medical Sciences" },
  { code: "DMLL", title: "Modern Languages & Literature" },
  { code: "DNDO", title: "Endodontics" },
  { code: "DORL", title: "Oral Medicine" },
  { code: "DPED", title: "Pediatric Dentistry" },
  { code: "DPER", title: "Periodontics" },
  { code: "DPHC", title: "Dental Public Health" },
  { code: "DRTH", title: "Orthodontics" },
  { code: "DSCI", title: "Data Science" },
  { code: "DSPR", title: "Disease Processes" },
  { code: "DSRE", title: "Disease & Restoration of Hlth" },
  { code: "EBME", title: "Biomedical Engineering" },
  { code: "ECES", title: "Electrical Engr & Comp Sci" },
  { code: "ECHE", title: "Chemical Engineering" },
  { code: "ECIV", title: "Civil Engineering" },
  { code: "ECLE", title: "Early Clinical Experience" },
  { code: "ECMP", title: "Computer Engineering" },
  { code: "ECON", title: "Economics" },
  { code: "ECSE", title: "Electr., Computer, Systems Eng" },
  { code: "EDAB", title: "Education Abroad" },
  { code: "EDJC", title: "Education - John Carroll Univ" },
  { code: "EDMP", title: "Executive Doctor of Management" },
  { code: "EDUC", title: "Education" },
  { code: "EEAP", title: "Elec Engr & Applied Physics" },
  { code: "EECS", title: "Electrical Engr & Comp Sci" },
  { code: "EEPS", title: "Earth, Environ & Planetary Sci" },
  { code: "EFDA", title: "Expanded Function Dental Aux" },
  { code: "EFTS", title: "Fluid and Thermal Science" },
  { code: "EIND", title: "Industrial Engineering" },
  { code: "EMAC", title: "Macromolecular/Polymer Science" },
  { code: "EMAE", title: "Mechanical & Aerospace Engr" },
  { code: "EMBA", title: "Executive MBA" },
  { code: "EMCH", title: "Mechanical Engineering" },
  { code: "EMMD", title: "Emergency Med & Intensive Care" },
  { code: "EMMS", title: "Metallurgy & Materials Science" },
  { code: "EMSE", title: "Materials Science & Engineerng" },
  { code: "ENDO", title: "Endocrinology" },
  { code: "ENG	", title: "   English" },
  { code: "ENGD", title: "Engineering Drawing" },
  { code: "ENGL", title: "English" },
  { code: "ENGR", title: "Engineering Science" },
  { code: "ENTP", title: "Entrepreneurship" },
  { code: "EPBI", title: "Epidemiology & Biostatistics" },
  { code: "EPOM", title: "Pract Oriented Engr Mast Prog" },
  { code: "EQUI", title: "Out-of-Town Equivalency" },
  { code: "ERAS", title: "Erasmus Univ, Netherlands" },
  { code: "ERTH", title: "Earth Sciences" },
  { code: "ESAD", title: "Esade Business School, Spain" },
  { code: "ESCI", title: "Systems Ctrl & Industrial Engr" },
  { code: "ESMD", title: "Solid Mech, Struct & Mech Des" },
  { code: "ESTD", title: "Environmental Studies" },
  { code: "ESYS", title: "Systems Engineering" },
  { code: "ETHC", title: "Ethics" },
  { code: "ETHS", title: "Ethnic Studies" },
  { code: "EVHS", title: "Environmental Health Studies" },
  { code: "EXAM", title: "Examination Master/Ph.D." },
  { code: "EXCH", title: "International Exchange Program" },
  { code: "FAMC", title: "Family Medicine Core" },
  { code: "FAMD", title: "Family Medicine" },
  { code: "FRCH", title: "French" },
  { code: "FRSS", title: "Freshman Special Studies" },
  { code: "FSAE", title: "First Seminar Academic English" },
  { code: "FSCC", title: "First Seminar Common Curric" },
  { code: "FSCS", title: "First Seminar Cont Semester" },
  { code: "FSNA", title: "First Seminar Natural World" },
  { code: "FSSO", title: "First Seminar Social World" },
  { code: "FSSY", title: "First Seminar Symbolic World" },
  { code: "FSTS", title: "First Seminar Transfer Supplem" },
  { code: "FTEC", title: "FinTech" },
  { code: "FUND", title: "Fundesem Bus Schl, Spain" },
  { code: "GAST", title: "Gastroenterology" },
  { code: "GEMD", title: "Geriatric Medicine" },
  { code: "GENE", title: "Genetics" },
  { code: "GEOG", title: "Geography" },
  { code: "GEOL", title: "Geology" },
  { code: "GEOM", title: "Geographic Medicine" },
  { code: "GERI", title: "Geriatric Medicine" },
  { code: "GERM", title: "German" },
  { code: "GERO", title: "Gerontological Studies" },
  { code: "GMBA", title: "Global MBA" },
  { code: "GRAD", title: "Graduate Studies" },
  { code: "GREK", title: "Greek" },
  { code: "GRMN", title: "German" },
  { code: "GTOX", title: "Genetic Toxicology" },
  { code: "HBRW", title: "Hebrew" },
  { code: "HDEV", title: "Interdisc Prog: Hum Developmnt" },
  { code: "HEAL", title: "Health Science" },
  { code: "HEMA", title: "Hematology/Oncology" },
  { code: "HEWB", title: "Health & Well-Being" },
  { code: "HIER", title: "Egyptian Hieroglyphs" },
  { code: "HLTH", title: "Community Health" },
  { code: "HPSC", title: "History & Philosophy of Sci" },
  { code: "HS	 ", title: "  Humanities and Social Studies" },
  { code: "HSED", title: "Health Sciences Education" },
  { code: "HSMC", title: "Health Systems Management" },
  { code: "HSST", title: "Hist of Science & Technology" },
  { code: "HSTY", title: "History" },
  { code: "HUMN", title: "Humanities" },
  { code: "HWDP", title: "Health Disease and Processes" },
  { code: "IBIS", title: "Integrated Biological Sciences" },
  { code: "IBMS", title: "Integrated Biological Studies" },
  { code: "IDHS", title: "Interdisciplinary Health Stud" },
  { code: "IDRL", title: "Industrial Relations" },
  { code: "IECS", title: "IECS Strasbourg, France" },
  { code: "IHSC", title: "Interdisciplinary Health Sci" },
  { code: "IIME", title: "Inst for Integr of Mgmt & Engr" },
  { code: "IMED", title: "Internal Medicine" },
  { code: "IMMU", title: "Immunology & Infectious Dis" },
  { code: "INCA", title: "Incae in Alajuela, Costa Rica" },
  { code: "INQU", title: "Inquiry" },
  { code: "INTH", title: "International Health" },
  { code: "INTL", title: "International Studies" },
  { code: "IPOD", title: "Positive Organztnl Devel-India" },
  { code: "ITAL", title: "Italian" },
  { code: "ITAM", title: "Ind Tech Inst of Mexico (Itam)" },
  { code: "JAPN", title: "Japanese" },
  { code: "JDST", title: "Judaic Studies" },
  { code: "JRAB", title: "Junior Year Abroad" },
  { code: "LAPP", title: "Law & Public Policy" },
  { code: "LATN", title: "Latin" },
  { code: "LAWS", title: "Law" },
  { code: "LCAN", title: "Canadian Law Courses" },
  { code: "LDRS", title: "Leadership" },
  { code: "LEAP", title: "Leadership Excel & Achieve" },
  { code: "LEGL", title: "Legal Studies" },
  { code: "LHRP", title: "Labor & Human Resource Policy" },
  { code: "LIBS", title: "Library Science" },
  { code: "LING", title: "Linguistics" },
  { code: "LINS", title: "Law Summer Institute" },
  { code: "LITR", title: "Literature" },
  { code: "LLM	", title: "   LL.M. Tax Program" },
  { code: "LMON", title: "Montreal Law Courses" },
  { code: "LSAB", title: "Law School Study Abroad" },
  { code: "LYON", title: "Lyon" },
  { code: "M	  ", title: " Mathematics" },
  { code: "MAHE", title: "Maintenance of Health" },
  { code: "MANC", title: "University of Manchester" },
  { code: "MAND", title: "Mandel Center" },
  { code: "MASS", title: "Medicine and Social Structures" },
  { code: "MATH", title: "Mathematics" },
  { code: "MBAC", title: "MBA Core" },
  { code: "MBAP", title: "MBA Part Time Cohort" },
  { code: "MBIO", title: "Molecular Biol & Microbiology" },
  { code: "MEDC", title: "Medicine Core Clerkship" },
  { code: "MEDG", title: "General Medicine" },
  { code: "MEDS", title: "Medical Basic Science Curr" },
  { code: "MEDT", title: "Medical Technology" },
  { code: "MGAB", title: "Management Study Abroad" },
  { code: "MGMT", title: "Management" },
  { code: "MGRD", title: "Schl of Med Graduate Education" },
  { code: "MIDS", title: "Information Systems" },
  { code: "MILT", title: "   SRV	Military Services" },
  { code: "MISC", title: "Miscellaneous" },
  { code: "MKMR", title: "Marketing" },
  { code: "MLIT", title: "Modern Foreign Lit & Mod Lang" },
  { code: "MLSC", title: "Military Science" },
  { code: "MMED", title: "Molecular Medicine" },
  { code: "MONT", title: "Inst Tecn Estd Sup Mnt, Mexico" },
  { code: "MPHP", title: "Public Health" },
  { code: "MPOD", title: "Positive Organizational Devel" },
  { code: "MRKM", title: "Marketing and Merchandising" },
  { code: "MSBA", title: "MSM in Business Analytics" },
  { code: "MSFC", title: "MSM in Finance-China" },
  { code: "MSFI", title: "MSM in Finance" },
  { code: "MSOD", title: "Manifestations of Disease" },
  { code: "MSOR", title: "Master of Sci in Oper Research" },
  { code: "MSPL", title: "Master of Sci in Pstve Ldrshp" },
  { code: "MSTP", title: "Med Scientist Training Program" },
  { code: "MUAP", title: "Applied Music" },
  { code: "MUAR", title: "Music, Audio Recording" },
  { code: "MUCP", title: "Music, Composition" },
  { code: "MUDE", title: "Music, Dalcroze/Eurhythmics" },
  { code: "MUED", title: "Music, Education" },
  { code: "MUEN", title: "Music, Ensembles" },
  { code: "MUGN", title: "Music, General/Misc" },
  { code: "MUHI", title: "Music History" },
  { code: "MULI", title: "Music Literature" },
  { code: "MUPD", title: "Music, Pedagogy" },
  { code: "MUPM", title: "Music, Popular" },
  { code: "MURP", title: "Music, Repertoire" },
  { code: "MUSC", title: "Music" },
  { code: "MUSD", title: "Doctor Musical Arts" },
  { code: "MUSP", title: "Music, Secondary Performance" },
  { code: "MUTH", title: "Music Theory" },
  { code: "MVIR", title: "Molecular Virology Train Prog" },
  { code: "NEUM", title: "Neurological Medicine" },
  { code: "NEUR", title: "Neurosciences" },
  { code: "NEUS", title: "Neurosurgery" },
  { code: "NORG", title: "Norwegian Schl of Mgmt, Norway" },
  { code: "NSCI", title: "Neuroscience" },
  { code: "NTRN", title: "Nutrition" },
  { code: "NUAN", title: "Nursing Anesthesiology" },
  { code: "NUED", title: "Nursing Education" },
  { code: "NUMN", title: "Master of Nursing" },
  { code: "NUND", title: "Doctor of Nursing" },
  { code: "NUNI", title: "Nursing Informatics" },
  { code: "NUNP", title: "Nurse Practitioner" },
  { code: "NURS", title: "Nursing" },
  { code: "OBGC", title: "OB/Gyn Core Clerkship" },
  { code: "OBGY", title: "Obstetrics/Gynecology" },
  { code: "OMFS", title: "Oral & Maxillofacial Surgery" },
  { code: "OPMT", title: "Operations Management" },
  { code: "OPRE", title: "Operations Research" },
  { code: "OPTH", title: "Ophthalmology" },
  { code: "ORAD", title: "Organization and Administratn" },
  { code: "ORBH", title: "Organizational Behavior" },
  { code: "ORIG", title: "Origins" },
  { code: "ORTH", title: "Orthopaedic Surgery" },
  { code: "OTHR", title: "Other" },
  { code: "OTOL", title: "Otolaryngology" },
  { code: "P	  ", title: " Physics" },
  { code: "PAST", title: "Physician Assistant Studies" },
  { code: "PATH", title: "Pathology" },
  { code: "PBPG", title: "Patient Based Program" },
  { code: "PE	 ", title: "  Physical Education" },
  { code: "PEDC", title: "Pediatrics Core Clerkship" },
  { code: "PEDS", title: "Pediatrics" },
  { code: "PGOD", title: "Pathogenesis of Disease" },
  { code: "PHED", title: "Physical Education" },
  { code: "PHIL", title: "Philosophy" },
  { code: "PHOL", title: "Physiology & Biophysics" },
  { code: "PHRM", title: "Pharmacology" },
  { code: "PHYS", title: "Physics" },
  { code: "PLCY", title: "Management Policy" },
  { code: "PORT", title: "Portuguese" },
  { code: "POSC", title: "Political Science" },
  { code: "PQHS", title: "Popn & Quant Health Sci" },
  { code: "PRAC", title: "Practicum" },
  { code: "PSCL", title: "Psychology" },
  { code: "PSYC", title: "Psychiatry Core Clerkship" },
  { code: "PSYY", title: "Psychiatry" },
  { code: "PULM", title: "Pulmonary Medicine" },
  { code: "QUMM", title: "Quantitative Methods in Mgmt" },
  { code: "RADI", title: "Radiology" },
  { code: "RAON", title: "Radiation Oncology" },
  { code: "RASE", title: "Research & Special Electives" },
  { code: "RBIO", title: "Reproductive Biology" },
  { code: "READ", title: "Reading & Learning Strategies" },
  { code: "REHA", title: "Rehab Med/Occupational Hlth" },
  { code: "REHE", title: "Restoration of Health" },
  { code: "REMA", title: "Restoration & Mainten of Hlth" },
  { code: "RENL", title: "Renal/Nephrology" },
  { code: "RESC", title: "Research Curriculum" },
  { code: "RGME", title: "Regenerative Med Entrprnrshp" },
  { code: "RHEU", title: "Clinical Rheumatology" },
  { code: "RLGN", title: "Religious Studies" },
  { code: "RSCH", title: "Graduate Summer Research" },
  { code: "RUSN", title: "Russian" },
  { code: "SASS", title: "School of Applied Soc Sciences" },
  { code: "SCMG", title: "Supply Chain Management" },
  { code: "SCPP", title: "Science and Public Policy" },
  { code: "SIDS", title: "Spec Interdisciplinary Studies" },
  { code: "SJUS", title: "Social Justice" },
  { code: "SMAB", title: "Semester in Absentia" },
  { code: "SOCI", title: "Sociology" },
  { code: "SPAN", title: "Spanish" },
  { code: "SPCH", title: "Speech Communication" },
  { code: "SPPP", title: "Problems/Policy Program" },
  { code: "SPSM", title: "Special Studies in Medicine" },
  { code: "SRAB", title: "Senior In Absentia" },
  { code: "SRCH", title: "Social Work Research" },
  { code: "SSBT", title: "Sociobehavioral Theory" },
  { code: "SSCI", title: "Social Sciences" },
  { code: "SSWM", title: "Social Work Methods" },
  { code: "STAT", title: "Statistics" },
  { code: "SURC", title: "Surgery Core Clerkship" },
  { code: "SURG", title: "Surgery" },
  { code: "SWBC", title: "SASS-SW Meth Elec B/C Stream" },
  { code: "SYBB", title: "Systems Biology and Bioinform" },
  { code: "SYPS", title: "Senior Year in Prof Studies" },
  { code: "TELA", title: "Tel-Aviv University, Israel" },
  { code: "THTR", title: "Theater Arts" },
  { code: "UCAP", title: "SAGES Capstone Experience" },
  { code: "UGSP", title: "Undergraduate Scholars Prog" },
  { code: "UNEL", title: "Unlisted Elective" },
  { code: "UNIV", title: "University Studies" },
  { code: "URES", title: "Urban & Environmental Studies" },
  { code: "UROL", title: "Urology" },
  { code: "USEM", title: "University Seminar" },
  { code: "USFS", title: "University Seminars First Sem" },
  { code: "USNA", title: "Think About The Natural World" },
  { code: "USSO", title: "Think About The Social World" },
  { code: "USSY", title: "Think About The Symbolic World" },
  { code: "VACA", title: "Vacation" },
  { code: "VEAL", title: "Veale Entrepreneurship Institute" },
  { code: "WASH", title: "Washington Semester" },
  { code: "WGST", title: "Women's & Gender Studies" },
  { code: "WHUK", title: "Otto Beisheim Grd Schl, Germn" },
  { code: "WIEN", title: "Vienna Univ of Econ, Austria" },
  { code: "WKAB", title: "Work in Absentia" },
  { code: "WLIT", title: "World Literature" },
  { code: "WMST", title: "Women's & Gender Studies" },
  { code: "WSTD", title: "Women's Studies" },
  { code: "YORK", title: "York University, Canada" },
];
